apiVersion: v1
kind: Service
metadata:
  name: hospital-frontend
  namespace: hospital
  labels:
    app: hospital-frontend
spec:
  type: NodePort
  selector:
    app: hospital-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
